version: '3.3'
services:
  inn-checker-stage:
    image: inn-checker
    restart: always
    ports:
      - 80:80
    links:
      - inn-checker-stage-store:db
    environment:
      DB_USERNAME: inn_checker
      DB_PASSWORD: R1#_42!2o
      DB_NAME: inn_checker_stage
      DB_HOST: db
      APP_PORT: 80
      # mix phx.gen.secret
      SECRET_KEY_BASE: bvcbcEkg8BO+2WP84yvvIlSYvxl5/1okLPTSY32q3haLopLZjHACQbDzeRR7Rnoi
      SERVER_HOST: localhost
      SERVER_PORT: 80
      # 24 |> :crypto.strong_rand_bytes() |> Base.encode64
      SERVER_LIVE_SALT: +W386VsinWfla28cT56R0f6ZJNCQbBUL
  inn-checker-stage-store:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./db_data:/data
    environment:
      LANG: ru_RU.utf8
      PGDATA: /data
      POSTGRES_DB: inn_checker_stage
      POSTGRES_USER: inn_checker
      POSTGRES_PASSWORD: R1#_42!2o
